# gokaygurcan/dockerfile-certbot

language: bash
services: docker

sudo: false

git:
  depth: 1

before_script:
  - docker version
  - docker info

script:
  - docker build --rm -t gokaygurcan/certbot:test .
  - docker run --rm -d --name certbot gokaygurcan/certbot:test certbot --version

notifications:
  email: false
