# gokaygurcan/dockerfile-certbot

name: 'Certbot'

on:
  push:
  pull_request:
    branches:
    - master

env:
  GITHUB: ${{ toJson(github) }}

jobs:
  certbot:
    name: 'certbot'
    runs-on: 'ubuntu-latest'
    env:
      CI: true
    steps:
    - id: 'checkout'
      name: 'Checkout'
      uses: 'actions/checkout@v2'

    - id: 'login'
      name: 'Login to Docker Hub'
      uses: 'actions-hub/docker/login@master'
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - id: 'build'
      name: 'Build image'
      run: |
        docker build --file Dockerfile --tag gokaygurcan/certbot:latest .

    - id: 'test'
      name: 'Test'
      run: |
        docker run --rm --name certbot gokaygurcan/certbot:latest certbot --version

    - id: 'push'
      name: 'Push to Docker Registry'
      uses: 'actions-hub/docker@master'
      if: github.ref == 'refs/heads/master'
      with:
        args: push gokaygurcan/certbot:latest
