# gokaygurcan/dockerfile-certbot

name: Certbot

on:
  push:
  pull_request:
    branches:
    - main

env:
  GITHUB: ${{ toJson(github) }}

jobs:
  certbot:
    name: Certbot
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3

    - id: login
      name: Login to Docker Hub
      uses: docker/login-action@v2
      if: |
        github.ref == 'refs/heads/main'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: build
      name: Build image
      run: |
        docker build --file Dockerfile --tag gokaygurcan/certbot:latest .
        docker ps -a

    - id: test
      name: Test
      run: |
        docker run --rm --name certbot gokaygurcan/certbot:latest certbot --version

    - id: push
      name: Push to Docker Registry
      uses: docker/build-push-action@v3
      if: |
        github.ref == 'refs/heads/main'
      with:
        context: .
        push: true
        tags: gokaygurcan/certbot:latest
